# Generated by Django 4.2.7 on 2024-01-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Savollar bazasi'},
        ),
    ]
