# Generated by Django 4.2.7 on 2024-01-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_file_options_alter_homeaboutme_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='sliders')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
    ]
