# Generated by Django 4.2.7 on 2024-01-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_homeslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'ordering': ['-id'], 'verbose_name_plural': '11. Slayder'},
        ),
    ]
