# Generated by Django 4.2.7 on 2024-01-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_homeslider_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='homeslider',
            name='button_title',
        ),
    ]
