# Generated by Django 4.2.7 on 2024-01-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_amaliy_yuklashlar_soni_maruza_yuklashlar_soni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labaratoriyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fan', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('labaratoriya_fayl', models.FileField(upload_to='labaratoriyalar')),
            ],
            options={
                'verbose_name_plural': 'Labaratoriyalar',
                'ordering': ['-id'],
            },
        ),
    ]
