# Generated by Django 4.2.7 on 2024-01-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_labaratoriyalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='labaratoriyalar',
            name='yuklashlar_soni',
            field=models.BigIntegerField(default=0),
        ),
    ]
