# Generated by Django 4.2.7 on 2024-11-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_labaratoriyalar_yuklashlar_soni'),
    ]

    operations = [
        migrations.AddField(
            model_name='amaliy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='amaliylar'),
        ),
        migrations.AddField(
            model_name='labaratoriyalar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='labaratoriyalar'),
        ),
        migrations.AddField(
            model_name='maruza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maruzalar'),
        ),
    ]
